apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: vaibhavnitor/backend-test-image:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__Database
          value: "Server=34.230.201.223,1433;Database=ElectricDB;User Id=sa;Password=test@123"
        - name: jwtConfig__Key
          value: "Bhaskarmehtajharkhand"
        - name: jwtConfig__Duration
          value: "1"
